//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SML.DAL.DBEdmx
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class SongTable
    {
        public int SongID { get; set; }
        public string SongName { get; set; }
    [DataType(DataType.MultilineText)]
    public string Lyrics { get; set; }
        public string Artist { get; set; }
        public int UserId { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
